# 基本数据对象及操作

## 1. Series

* 创建Series

In [36]:
import pandas as pd

countries = ['中国', '美国', '澳大利亚']
countries_s = pd.Series(countries)
print(type(countries_s))
print(countries_s)

<class 'pandas.core.series.Series'>
0      中国
1      美国
2    澳大利亚
dtype: object

In [37]:
numbers = [4, 5, 6]
print(pd.Series(numbers))

0    4
1    5
2    6
dtype: int64

In [38]:
country_dicts = {'CH': '中国',
                'US': '美国',
                'AU': '澳大利亚'}

country_dict_s = pd.Series(country_dicts)
# 给索引命名
country_dict_s.index.name = 'Code'
# 给数据命名
country_dict_s.name = 'Country'

print(country_dict_s)
print(country_dict_s.values)
print(country_dict_s.index)

Code
AU    澳大利亚
CH      中国
US      美国
Name: Country, dtype: object
['澳大利亚' '中国' '美国']
Index(['AU', 'CH', 'US'], dtype='object', name='Code')

* 处理缺失数据

In [39]:
countries = ['中国', '美国', '澳大利亚', None]
print(pd.Series(countries))

0      中国
1      美国
2    澳大利亚
3    None
dtype: object

In [40]:
numbers = [4, 5, 6, None]
print(pd.Series(numbers))

0    4.0
1    5.0
2    6.0
3    NaN
dtype: float64

* Series 索引

In [41]:
country_dicts = {'CH': '中国',
                'US': '美国',
                'AU': '澳大利亚'}

country_dict_s = pd.Series(country_dicts)
print(country_dict_s)

AU    澳大利亚
CH      中国
US      美国
dtype: object

In [42]:
# 通过索引判断数据是存在
# Series也可看作定长、有序的字典
print('CH' in country_dict_s)
print('NZ' in country_dict_s)

True
False

In [43]:
print('iloc:', country_dict_s.iloc[1])
print('loc:', country_dict_s.loc['US'])
print('[]:', country_dict_s['US'])

iloc: 中国
loc: 美国
[]: 美国

In [44]:
print('iloc:\n', country_dict_s.iloc[ [0, 2] ])
print()
print('loc:\n', country_dict_s.loc[['US', 'AU']])

iloc:
 AU    澳大利亚
US      美国
dtype: object

loc:
 US      美国
AU    澳大利亚
dtype: object

*  向量化操作

In [45]:
import numpy as np

s = pd.Series(np.random.randint(0, 1000, 10000))
print(s.head())
print(len(s))

0    712
1    522
2    623
3    451
4    765
dtype: int32
10000

In [46]:
%%timeit -n 100
total = 0
for item in s:
    total += item

100 loops, best of 3: 918 µs per loop

In [47]:
%%timeit -n 100
total = np.sum(s)

100 loops, best of 3: 91.1 µs per loop

In [48]:
%%timeit -n 10
s = pd.Series(np.random.randint(0, 1000, 10000))
for label, value in s.iteritems():
    s.loc[label] = value + 2

10 loops, best of 3: 635 ms per loop

In [49]:
%%timeit -n 10
s = pd.Series(np.random.randint(0, 1000, 10000))
s += 2

10 loops, best of 3: 238 µs per loop

## 2. DataFrame

* 创建Dataframe

In [1]:
import pandas as pd

country1 = pd.Series({'Name': '中国',
                    'Language': 'Chinese',
                    'Area': '9.597M km2',
                     'Happiness Rank': 79})

country2 = pd.Series({'Name': '美国',
                    'Language': 'English (US)',
                    'Area': '9.834M km2',
                     'Happiness Rank': 14})

country3 = pd.Series({'Name': '澳大利亚',
                    'Language': 'English (AU)',
                    'Area': '7.692M km2',
                     'Happiness Rank': 9})

df = pd.DataFrame([country1, country2, country3], index=['CH', 'US', 'AU'])

In [2]:
# 注意在jupyter中使用print和不使用print的区别
print(df)
df

          Area  Happiness Rank      Language  Name
CH  9.597M km2              79       Chinese    中国
US  9.834M km2              14  English (US)    美国
AU  7.692M km2               9  English (AU)  澳大利亚

          Area  Happiness Rank      Language  Name
CH  9.597M km2              79       Chinese    中国
US  9.834M km2              14  English (US)    美国
AU  7.692M km2               9  English (AU)  澳大利亚

In [3]:
# 添加数据
# 如果个数小于要求的个数，会自动进行“广播”操作
# 如果大于要求的个数，会报错
df['Location'] = '地球'
print(df)

df['Region'] = ['亚洲', '北美洲', '大洋洲']
# print(df)
df

          Area  Happiness Rank      Language  Name Location
CH  9.597M km2              79       Chinese    中国       地球
US  9.834M km2              14  English (US)    美国       地球
AU  7.692M km2               9  English (AU)  澳大利亚       地球

          Area  Happiness Rank      Language  Name Location Region
CH  9.597M km2              79       Chinese    中国       地球     亚洲
US  9.834M km2              14  English (US)    美国       地球    北美洲
AU  7.692M km2               9  English (AU)  澳大利亚       地球    大洋洲

* Dataframe索引

In [4]:
# 行索引
print('loc:')
print(df.loc['CH'])
print(type(df.loc['CH']))

print('iloc:')
print(df.iloc[1])

print(df['Area'])

loc:
Area              9.597M km2
Happiness Rank            79
Language             Chinese
Name                      中国
Location                  地球
Region                    亚洲
Name: CH, dtype: object
<class 'pandas.core.series.Series'>
iloc:
Area                9.834M km2
Happiness Rank              14
Language          English (US)
Name                        美国
Location                    地球
Region                     北美洲
Name: US, dtype: object
CH    9.597M km2
US    9.834M km2
AU    7.692M km2
Name: Area, dtype: object

In [5]:
# 列索引
print(df['Area'])
print(type(df['Area']))

CH    9.597M km2
US    9.834M km2
AU    7.692M km2
Name: Area, dtype: object
<class 'pandas.core.series.Series'>

In [6]:
# 获取不连续的列数据
print(df[['Name', 'Area']])

    Name        Area
CH    中国  9.597M km2
US    美国  9.834M km2
AU  澳大利亚  7.692M km2

In [7]:
# 混合索引
# 注意写法上的区别
print('先取出列，再取行：')
print(df['Area']['CH'])
print(df['Area'].loc['CH'])
print(df['Area'].iloc[0])

print('先取出行，再取列：')
print(df.loc['CH']['Area'])
print(df.iloc[0]['Area'])

先取出列，再取行：
9.597M km2
9.597M km2
9.597M km2
先取出行，再取列：
9.597M km2
9.597M km2

In [8]:
# 转换行和列
print(df.T)

                        CH            US            AU
Area            9.597M km2    9.834M km2    7.692M km2
Happiness Rank          79            14             9
Language           Chinese  English (US)  English (AU)
Name                    中国            美国          澳大利亚
Location                地球            地球            地球
Region                  亚洲           北美洲           大洋洲

* 删除数据

In [9]:
print(df.drop(['CH']))
# 注意drop操作只是将修改后的数据copy一份，而不会对原始数据进行修改
print(df)

          Area  Happiness Rank      Language  Name Location Region
US  9.834M km2              14  English (US)    美国       地球    北美洲
AU  7.692M km2               9  English (AU)  澳大利亚       地球    大洋洲
          Area  Happiness Rank      Language  Name Location Region
CH  9.597M km2              79       Chinese    中国       地球     亚洲
US  9.834M km2              14  English (US)    美国       地球    北美洲
AU  7.692M km2               9  English (AU)  澳大利亚       地球    大洋洲

In [10]:
print(df.drop(['CH'], inplace=True))
# 如果使用了inplace=True，会在原始数据上进行修改，同时不会返回一个copy
print(df)

None
          Area  Happiness Rank      Language  Name Location Region
US  9.834M km2              14  English (US)    美国       地球    北美洲
AU  7.692M km2               9  English (AU)  澳大利亚       地球    大洋洲

In [11]:
#  如果需要删除列，需要指定axis=1
print(df.drop(['Area'], axis=1))
print(df)

    Happiness Rank      Language  Name Location Region
US              14  English (US)    美国       地球    北美洲
AU               9  English (AU)  澳大利亚       地球    大洋洲
          Area  Happiness Rank      Language  Name Location Region
US  9.834M km2              14  English (US)    美国       地球    北美洲
AU  7.692M km2               9  English (AU)  澳大利亚       地球    大洋洲

In [12]:
# 也可直接使用del关键字
del df['Name']
print(df)

          Area  Happiness Rank      Language Location Region
US  9.834M km2              14  English (US)       地球    北美洲
AU  7.692M km2               9  English (AU)       地球    大洋洲

* DataFrame的操作与加载

In [13]:
df['Happiness Rank']

US    14
AU     9
Name: Happiness Rank, dtype: int64

In [14]:
# 注意从DataFrame中取出的数据进行操作后，会对原始数据产生影响
ranks = df['Happiness Rank']
ranks += 2
print(ranks)
print(df)

US    16
AU    11
Name: Happiness Rank, dtype: int64
          Area  Happiness Rank      Language Location Region
US  9.834M km2              16  English (US)       地球    北美洲
AU  7.692M km2              11  English (AU)       地球    大洋洲

In [15]:
# 注意从DataFrame中取出的数据进行操作后，会对原始数据产生影响
# 安全的操作是使用copy()
ranks = df['Happiness Rank'].copy()
ranks += 2
print(ranks)
print(df)

US    18
AU    13
Name: Happiness Rank, dtype: int64
          Area  Happiness Rank      Language Location Region
US  9.834M km2              16  English (US)       地球    北美洲
AU  7.692M km2              11  English (AU)       地球    大洋洲

In [16]:
# 加载csv文件数据
reprot_2015_df = pd.read_csv('./2015.csv')
print('2015年数据预览：')
#print(reprot_2015_df.head())
reprot_2015_df.head()

2015年数据预览：

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [17]:
print(reprot_2015_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
Country                          158 non-null object
Region                           158 non-null object
Happiness Rank                   158 non-null int64
Happiness Score                  158 non-null float64
Standard Error                   158 non-null float64
Economy (GDP per Capita)         158 non-null float64
Family                           158 non-null float64
Health (Life Expectancy)         158 non-null float64
Freedom                          158 non-null float64
Trust (Government Corruption)    158 non-null float64
Generosity                       158 non-null float64
Dystopia Residual                158 non-null float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB
None

## 3. 索引

In [18]:
# 使用index_col指定索引列
# 使用usecols指定需要读取的列
reprot_2016_df = pd.read_csv('./2016.csv', 
                             index_col='Country',
                             usecols=['Country', 'Happiness Rank', 'Happiness Score', 'Region'])
# 数据预览
reprot_2016_df.head()

                     Region  Happiness Rank  Happiness Score
Country
Denmark      Western Europe               1            7.526
Switzerland  Western Europe               2            7.509
Iceland      Western Europe               3            7.501
Norway       Western Europe               4            7.498
Finland      Western Europe               5            7.413

In [19]:
print('列名(column)：', reprot_2016_df.columns)
print('行名(index)：', reprot_2016_df.index)

列名(column)： Index(['Region', 'Happiness Rank', 'Happiness Score'], dtype='object')
行名(index)： Index(['Denmark', 'Switzerland', 'Iceland', 'Norway', 'Finland', 'Canada',
       'Netherlands', 'New Zealand', 'Australia', 'Sweden',
       ...
       'Madagascar', 'Tanzania', 'Liberia', 'Guinea', 'Rwanda', 'Benin',
       'Afghanistan', 'Togo', 'Syria', 'Burundi'],
      dtype='object', name='Country', length=157)

In [20]:
# 注意index是不可变的
reprot_2016_df.index[0] = '丹麦'

TypeError: Index does not support mutable operations

In [21]:
# 重置index
# 注意inplace加与不加的区别
reprot_2016_df.reset_index(inplace=True)

In [22]:
reprot_2016_df.head()

       Country          Region  Happiness Rank  Happiness Score
0      Denmark  Western Europe               1            7.526
1  Switzerland  Western Europe               2            7.509
2      Iceland  Western Europe               3            7.501
3       Norway  Western Europe               4            7.498
4      Finland  Western Europe               5            7.413

In [23]:
# 重命名列名
reprot_2016_df = reprot_2016_df.rename(columns={'Region': '地区', 'Hapiness Rank': '排名', 'Hapiness Score': '幸福指数'})
reprot_2016_df.head()

       Country              地区  Happiness Rank  Happiness Score
0      Denmark  Western Europe               1            7.526
1  Switzerland  Western Europe               2            7.509
2      Iceland  Western Europe               3            7.501
3       Norway  Western Europe               4            7.498
4      Finland  Western Europe               5            7.413

In [24]:
# 重命名列名，注意inplace的使用
reprot_2016_df.rename(columns={'Region': '地区', 'Happiness Rank': '排名', 'Happiness Score': '幸福指数'},
                     inplace=True)
reprot_2016_df.head()

       Country              地区  排名   幸福指数
0      Denmark  Western Europe   1  7.526
1  Switzerland  Western Europe   2  7.509
2      Iceland  Western Europe   3  7.501
3       Norway  Western Europe   4  7.498
4      Finland  Western Europe   5  7.413

## 4. Boolean Mask

In [25]:
reprot_2016_df.head()

       Country              地区  排名   幸福指数
0      Denmark  Western Europe   1  7.526
1  Switzerland  Western Europe   2  7.509
2      Iceland  Western Europe   3  7.501
3       Norway  Western Europe   4  7.498
4      Finland  Western Europe   5  7.413

In [26]:
# 过滤 Western Europe 地区的国家
# only_western_europe = reprot_2016_df['地区'] == 'Western Europe'
reprot_2016_df[reprot_2016_df['地区'] == 'Western Europe']

           Country              地区  排名   幸福指数
0          Denmark  Western Europe   1  7.526
1      Switzerland  Western Europe   2  7.509
2          Iceland  Western Europe   3  7.501
3           Norway  Western Europe   4  7.498
4          Finland  Western Europe   5  7.413
6      Netherlands  Western Europe   7  7.339
9           Sweden  Western Europe  10  7.291
11         Austria  Western Europe  12  7.119
15         Germany  Western Europe  16  6.994
17         Belgium  Western Europe  18  6.929
18         Ireland  Western Europe  19  6.907
19      Luxembourg  Western Europe  20  6.871
22  United Kingdom  Western Europe  23  6.725
29           Malta  Western Europe  30  6.488
31          France  Western Europe  32  6.478
36           Spain  Western Europe  37  6.361
49           Italy  Western Europe  50  5.977
61    North Cyprus  Western Europe  62  5.771
68          Cyprus  Western Europe  69  5.546
93        Portugal  Western Europe  94  5.123
98          Greece  Western Europe  99  5.033

In [27]:
# 过滤 Western Europe 地区的国家
# 并且排名在10之外
only_western_europe_10 = (reprot_2016_df['地区'] == 'Western Europe') & (reprot_2016_df['排名'] > 10)
only_western_europe_10

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11      True
12     False
13     False
14     False
15      True
16     False
17      True
18      True
19      True
20     False
21     False
22      True
23     False
24     False
25     False
26     False
27     False
28     False
29      True
       ...
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
Length: 157, dtype: bool

In [28]:
# 叠加 boolean mask 得到最终结果
reprot_2016_df[only_western_europe_10]

           Country              地区  排名   幸福指数
11         Austria  Western Europe  12  7.119
15         Germany  Western Europe  16  6.994
17         Belgium  Western Europe  18  6.929
18         Ireland  Western Europe  19  6.907
19      Luxembourg  Western Europe  20  6.871
22  United Kingdom  Western Europe  23  6.725
29           Malta  Western Europe  30  6.488
31          France  Western Europe  32  6.478
36           Spain  Western Europe  37  6.361
49           Italy  Western Europe  50  5.977
61    North Cyprus  Western Europe  62  5.771
68          Cyprus  Western Europe  69  5.546
93        Portugal  Western Europe  94  5.123
98          Greece  Western Europe  99  5.033

In [29]:
# 熟练以后可以写在一行中
reprot_2016_df[(reprot_2016_df['地区'] == 'Western Europe') & (reprot_2016_df['排名'] > 10)]

           Country              地区  排名   幸福指数
11         Austria  Western Europe  12  7.119
15         Germany  Western Europe  16  6.994
17         Belgium  Western Europe  18  6.929
18         Ireland  Western Europe  19  6.907
19      Luxembourg  Western Europe  20  6.871
22  United Kingdom  Western Europe  23  6.725
29           Malta  Western Europe  30  6.488
31          France  Western Europe  32  6.478
36           Spain  Western Europe  37  6.361
49           Italy  Western Europe  50  5.977
61    North Cyprus  Western Europe  62  5.771
68          Cyprus  Western Europe  69  5.546
93        Portugal  Western Europe  94  5.123
98          Greece  Western Europe  99  5.033

## 5. 层级索引

In [30]:
reprot_2015_df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [31]:
# 设置层级索引
report_2015_df2 = reprot_2015_df.set_index(['Region', 'Country'])
report_2015_df2.head(20)

                                                      Happiness Rank  \
Region                          Country
Western Europe                  Switzerland                        1
                                Iceland                            2
                                Denmark                            3
                                Norway                             4
North America                   Canada                             5
Western Europe                  Finland                            6
                                Netherlands                        7
                                Sweden                             8
Australia and New Zealand       New Zealand                        9
                                Australia                         10
Middle East and Northern Africa Israel                            11
Latin America and Caribbean     Costa Rica                        12
Western Europe                  Austria                           13
Latin America and Caribbean     Mexico                            14
North America                   United States                     15
Latin America and Caribbean     Brazil                            16
Western Europe                  Luxembourg                        17
                                Ireland                           18
                                Belgium                           19
Middle East and Northern Africa United Arab Emirates              20

                                                      Happiness Score  \
Region                          Country
Western Europe                  Switzerland                     7.587
                                Iceland                         7.561
                                Denmark                         7.527
                                Norway                          7.522
North America                   Canada                          7.427
Western Europe                  Finland                         7.406
                                Netherlands                     7.378
                                Sweden                          7.364
Australia and New Zealand       New Zealand                     7.286
                                Australia                       7.284
Middle East and Northern Africa Israel                          7.278
Latin America and Caribbean     Costa Rica                      7.226
Western Europe                  Austria                         7.200
Latin America and Caribbean     Mexico                          7.187
North America                   United States                   7.119
Latin America and Caribbean     Brazil                          6.983
Western Europe                  Luxembourg                      6.946
                                Ireland                         6.940
                                Belgium                         6.937
Middle East and Northern Africa United Arab Emirates            6.901

                                                      Standard Error  \
Region                          Country
Western Europe                  Switzerland                  0.03411
                                Iceland                      0.04884
                                Denmark                      0.03328
                                Norway                       0.03880
North America                   Canada                       0.03553
Western Europe                  Finland                      0.03140
                                Netherlands                  0.02799
                                Sweden                       0.03157
Australia and New Zealand       New Zealand                  0.03371
                                Australia                    0.04083
Middle East and Northern Africa Israel                       0.03470
Latin America and Caribbean     Costa Rica                   0.04454
Western Europe                  Austria                      0.03751
Latin America and Caribbean     Mexico                       0.04176
North America                   United States                0.03839
Latin America and Caribbean     Brazil                       0.04076
Western Europe                  Luxembourg                   0.03499
                                Ireland                      0.03676
                                Belgium                      0.03595
Middle East and Northern Africa United Arab Emirates         0.03729

                                                      Economy (GDP per Capita)  \
Region                          Country
Western Europe                  Switzerland                            1.39651
                                Iceland                                1.30232
                                Denmark                                1.32548
                                Norway                                 1.45900
North America                   Canada                                 1.32629
Western Europe                  Finland                                1.29025
                                Netherlands                            1.32944
                                Sweden                                 1.33171
Australia and New Zealand       New Zealand                            1.25018
                                Australia                              1.33358
Middle East and Northern Africa Israel                                 1.22857
Latin America and Caribbean     Costa Rica                             0.95578
Western Europe                  Austria                                1.33723
Latin America and Caribbean     Mexico                                 1.02054
North America                   United States                          1.39451
Latin America and Caribbean     Brazil                                 0.98124
Western Europe                  Luxembourg                             1.56391
                                Ireland                                1.33596
                                Belgium                                1.30782
Middle East and Northern Africa United Arab Emirates                   1.42727

                                                       Family  \
Region                          Country
Western Europe                  Switzerland           1.34951
                                Iceland               1.40223
                                Denmark               1.36058
                                Norway                1.33095
North America                   Canada                1.32261
Western Europe                  Finland               1.31826
                                Netherlands           1.28017
                                Sweden                1.28907
Australia and New Zealand       New Zealand           1.31967
                                Australia             1.30923
Middle East and Northern Africa Israel                1.22393
Latin America and Caribbean     Costa Rica            1.23788
Western Europe                  Austria               1.29704
Latin America and Caribbean     Mexico                0.91451
North America                   United States         1.24711
Latin America and Caribbean     Brazil                1.23287
Western Europe                  Luxembourg            1.21963
                                Ireland               1.36948
                                Belgium               1.28566
Middle East and Northern Africa United Arab Emirates  1.12575

                                                      Health (Life Expectancy)  \
Region                          Country
Western Europe                  Switzerland                            0.94143
                                Iceland                                0.94784
                                Denmark                                0.87464
                                Norway                                 0.88521
North America                   Canada                                 0.90563
Western Europe                  Finland                                0.88911
                                Netherlands                            0.89284
                                Sweden                                 0.91087
Australia and New Zealand       New Zealand                            0.90837
                                Australia                              0.93156
Middle East and Northern Africa Israel                                 0.91387
Latin America and Caribbean     Costa Rica                             0.86027
Western Europe                  Austria                                0.89042
Latin America and Caribbean     Mexico                                 0.81444
North America                   United States                          0.86179
Latin America and Caribbean     Brazil                                 0.69702
Western Europe                  Luxembourg                             0.91894
                                Ireland                                0.89533
                                Belgium                                0.89667
Middle East and Northern Africa United Arab Emirates                   0.80925

                                                      Freedom  \
Region                          Country
Western Europe                  Switzerland           0.66557
                                Iceland               0.62877
                                Denmark               0.64938
                                Norway                0.66973
North America                   Canada                0.63297
Western Europe                  Finland               0.64169
                                Netherlands           0.61576
                                Sweden                0.65980
Australia and New Zealand       New Zealand           0.63938
                                Australia             0.65124
Middle East and Northern Africa Israel                0.41319
Latin America and Caribbean     Costa Rica            0.63376
Western Europe                  Austria               0.62433
Latin America and Caribbean     Mexico                0.48181
North America                   United States         0.54604
Latin America and Caribbean     Brazil                0.49049
Western Europe                  Luxembourg            0.61583
                                Ireland               0.61777
                                Belgium               0.58450
Middle East and Northern Africa United Arab Emirates  0.64157

                                                      Trust (Government Corruption)  \
Region                          Country
Western Europe                  Switzerland                                 0.41978
                                Iceland                                     0.14145
                                Denmark                                     0.48357
                                Norway                                      0.36503
North America                   Canada                                      0.32957
Western Europe                  Finland                                     0.41372
                                Netherlands                                 0.31814
                                Sweden                                      0.43844
Australia and New Zealand       New Zealand                                 0.42922
                                Australia                                   0.35637
Middle East and Northern Africa Israel                                      0.07785
Latin America and Caribbean     Costa Rica                                  0.10583
Western Europe                  Austria                                     0.18676
Latin America and Caribbean     Mexico                                      0.21312
North America                   United States                               0.15890
Latin America and Caribbean     Brazil                                      0.17521
Western Europe                  Luxembourg                                  0.37798
                                Ireland                                     0.28703
                                Belgium                                     0.22540
Middle East and Northern Africa United Arab Emirates                        0.38583

                                                      Generosity  \
Region                          Country
Western Europe                  Switzerland              0.29678
                                Iceland                  0.43630
                                Denmark                  0.34139
                                Norway                   0.34699
North America                   Canada                   0.45811
Western Europe                  Finland                  0.23351
                                Netherlands              0.47610
                                Sweden                   0.36262
Australia and New Zealand       New Zealand              0.47501
                                Australia                0.43562
Middle East and Northern Africa Israel                   0.33172
Latin America and Caribbean     Costa Rica               0.25497
Western Europe                  Austria                  0.33088
Latin America and Caribbean     Mexico                   0.14074
North America                   United States            0.40105
Latin America and Caribbean     Brazil                   0.14574
Western Europe                  Luxembourg               0.28034
                                Ireland                  0.45901
                                Belgium                  0.22250
Middle East and Northern Africa United Arab Emirates     0.26428

                                                      Dystopia Residual
Region                          Country
Western Europe                  Switzerland                     2.51738
                                Iceland                         2.70201
                                Denmark                         2.49204
                                Norway                          2.46531
North America                   Canada                          2.45176
Western Europe                  Finland                         2.61955
                                Netherlands                     2.46570
                                Sweden                          2.37119
Australia and New Zealand       New Zealand                     2.26425
                                Australia                       2.26646
Middle East and Northern Africa Israel                          3.08854
Latin America and Caribbean     Costa Rica                      3.17728
Western Europe                  Austria                         2.53320
Latin America and Caribbean     Mexico                          3.60214
North America                   United States                   2.51011
Latin America and Caribbean     Brazil                          3.26001
Western Europe                  Luxembourg                      1.96961
                                Ireland                         1.97570
                                Belgium                         2.41484
Middle East and Northern Africa United Arab Emirates            2.24743

In [32]:
# level0 索引
report_2015_df2.loc['Western Europe']

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
Country,,,,,,,,,,
Switzerland,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
Iceland,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
Denmark,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
Norway,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
Finland,6,7.406,0.03140,1.29025,1.31826,0.88911,0.64169,0.41372,0.23351,2.61955
Netherlands,7,7.378,0.02799,1.32944,1.28017,0.89284,0.61576,0.31814,0.47610,2.46570
Sweden,8,7.364,0.03157,1.33171,1.28907,0.91087,0.65980,0.43844,0.36262,2.37119
Austria,13,7.200,0.03751,1.33723,1.29704,0.89042,0.62433,0.18676,0.33088,2.53320
Luxembourg,17,6.946,0.03499,1.56391,1.21963,0.91894,0.61583,0.37798,0.28034,1.96961
Ireland,18,6.940,0.03676,1.33596,1.36948,0.89533,0.61777,0.28703,0.45901,1.97570
Belgium,19,6.937,0.03595,1.30782,1.28566,0.89667,0.58450,0.22540,0.22250,2.41484
United Kingdom,21,6.867,0.01866,1.26637,1.28548,0.90943,0.59625,0.32067,0.51912,1.96994
Germany,26,6.750,0.01848,1.32792,1.29937,0.89186,0.61477,0.21843,0.28214,2.11569
France,29,6.575,0.03512,1.27778,1.26038,0.94579,0.55011,0.20646,0.12332,2.21126
Spain,36,6.329,0.03468,1.23011,1.31379,0.95562,0.45951,0.06398,0.18227,2.12367
Malta,37,6.302,0.04206,1.20740,1.30203,0.88721,0.60365,0.13586,0.51752,1.64880
Italy,50,5.948,0.03914,1.25114,1.19777,0.95446,0.26236,0.02901,0.22823,2.02518
North Cyprus,66,5.695,0.05635,1.20806,1.07008,0.92356,0.49027,0.14280,0.26169,1.59888
Cyprus,67,5.689,0.05580,1.20813,0.89318,0.92356,0.40672,0.06146,0.30638,1.88931
Portugal,88,5.102,0.04802,1.15991,1.13935,0.87519,0.51469,0.01078,0.13719,1.26462
Greece,102,4.857,0.05062,1.15406,0.92933,0.88213,0.07699,0.01397,0.00000,1.80101

In [33]:
# 两层索引
report_2015_df2.loc['Western Europe', 'Switzerland']

Happiness Rank                   1.00000
Happiness Score                  7.58700
Standard Error                   0.03411
Economy (GDP per Capita)         1.39651
Family                           1.34951
Health (Life Expectancy)         0.94143
Freedom                          0.66557
Trust (Government Corruption)    0.41978
Generosity                       0.29678
Dystopia Residual                2.51738
Name: (Western Europe, Switzerland), dtype: float64

In [34]:
# 交换分层顺序
report_2015_df2.swaplevel()

,,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
Country,Region,,,,,,,,,,
Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
Finland,Western Europe,6,7.406,0.03140,1.29025,1.31826,0.88911,0.64169,0.41372,0.23351,2.61955
Netherlands,Western Europe,7,7.378,0.02799,1.32944,1.28017,0.89284,0.61576,0.31814,0.47610,2.46570
Sweden,Western Europe,8,7.364,0.03157,1.33171,1.28907,0.91087,0.65980,0.43844,0.36262,2.37119
New Zealand,Australia and New Zealand,9,7.286,0.03371,1.25018,1.31967,0.90837,0.63938,0.42922,0.47501,2.26425
Australia,Australia and New Zealand,10,7.284,0.04083,1.33358,1.30923,0.93156,0.65124,0.35637,0.43562,2.26646
Israel,Middle East and Northern Africa,11,7.278,0.03470,1.22857,1.22393,0.91387,0.41319,0.07785,0.33172,3.08854
Costa Rica,Latin America and Caribbean,12,7.226,0.04454,0.95578,1.23788,0.86027,0.63376,0.10583,0.25497,3.17728
Austria,Western Europe,13,7.200,0.03751,1.33723,1.29704,0.89042,0.62433,0.18676,0.33088,2.53320
Mexico,Latin America and Caribbean,14,7.187,0.04176,1.02054,0.91451,0.81444,0.48181,0.21312,0.14074,3.60214
United States,North America,15,7.119,0.03839,1.39451,1.24711,0.86179,0.54604,0.15890,0.40105,2.51011
Brazil,Latin America and Caribbean,16,6.983,0.04076,0.98124,1.23287,0.69702,0.49049,0.17521,0.14574,3.26001
Luxembourg,Western Europe,17,6.946,0.03499,1.56391,1.21963,0.91894,0.61583,0.37798,0.28034,1.96961
Ireland,Western Europe,18,6.940,0.03676,1.33596,1.36948,0.89533,0.61777,0.28703,0.45901,1.97570
Belgium,Western Europe,19,6.937,0.03595,1.30782,1.28566,0.89667,0.58450,0.22540,0.22250,2.41484
United Arab Emirates,Middle East and Northern Africa,20,6.901,0.03729,1.42727,1.12575,0.80925,0.64157,0.38583,0.26428,2.24743
United Kingdom,Western Europe,21,6.867,0.01866,1.26637,1.28548,0.90943,0.59625,0.32067,0.51912,1.96994
Oman,Middle East and Northern Africa,22,6.853,0.05335,1.36011,1.08182,0.76276,0.63274,0.32524,0.21542,2.47489
Venezuela,Latin America and Caribbean,23,6.810,0.06476,1.04424,1.25596,0.72052,0.42908,0.11069,0.05841,3.19131
Singapore,Southeastern Asia,24,6.798,0.03780,1.52186,1.02000,1.02525,0.54252,0.49210,0.31105,1.88501
Panama,Latin America and Caribbean,25,6.786,0.04910,1.06353,1.19850,0.79661,0.54210,0.09270,0.24434,2.84848
Germany,Western Europe,26,6.750,0.01848,1.32792,1.29937,0.89186,0.61477,0.21843,0.28214,2.11569
Chile,Latin America and Caribbean,27,6.670,0.05800,1.10715,1.12447,0.85857,0.44132,0.12869,0.33363,2.67585
Qatar,Middle East and Northern Africa,28,6.611,0.06257,1.69042,1.07860,0.79733,0.64040,0.52208,0.32573,1.55674
France,Western Europe,29,6.575,0.03512,1.27778,1.26038,0.94579,0.55011,0.20646,0.12332,2.21126
Argentina,Latin America and Caribbean,30,6.574,0.04612,1.05351,1.24823,0.78723,0.44974,0.08484,0.11451,2.83600
...,...,...,...,...,...,...,...,...,...,...,...
Myanmar,Southeastern Asia,129,4.307,0.04351,0.27108,0.70905,0.48246,0.44017,0.19034,0.79588,1.41805
Georgia,Central and Eastern Europe,130,4.297,0.04221,0.74190,0.38562,0.72926,0.40577,0.38331,0.05547,1.59541
Malawi,Sub-Saharan Africa,131,4.292,0.06130,0.01604,0.41134,0.22562,0.43054,0.06977,0.33128,2.80791
Sri Lanka,Southern Asia,132,4.271,0.03751,0.83524,1.01905,0.70806,0.53726,0.09179,0.40828,0.67108
Cameroon,Sub-Saharan Africa,133,4.252,0.04678,0.42250,0.88767,0.23402,0.49309,0.05786,0.20618,1.95071
Bulgaria,Central and Eastern Europe,134,4.218,0.04828,1.01216,1.10614,0.76649,0.30587,0.00872,0.11921,0.89991
Egypt,Middle East and Northern Africa,135,4.194,0.03260,0.88180,0.74700,0.61712,0.17288,0.06324,0.11291,1.59927
Yemen,Middle East and Northern Africa,136,4.077,0.04367,0.54649,0.68093,0.40064,0.35571,0.07854,0.09131,1.92313
Angola,Sub-Saharan Africa,137,4.033,0.04758,0.75778,0.86040,0.16683,0.10384,0.07122,0.12344,1.94939
Mali,Sub-Saharan Africa,138,3.995,0.05602,0.26074,1.03526,0.20583,0.38857,0.12352,0.18798,1.79293
Congo (Brazzaville),Sub-Saharan Africa,139,3.989,0.06682,0.67866,0.66290,0.31051,0.41466,0.11686,0.12388,1.68135
Comoros,Sub-Saharan Africa,140,3.956,0.04797,0.23906,0.79273,0.36315,0.22917,0.19900,0.17441,1.95812
Uganda,Sub-Saharan Africa,141,3.931,0.04317,0.21102,1.13299,0.33861,0.45727,0.07267,0.29066,1.42766
Senegal,Sub-Saharan Africa,142,3.904,0.03608,0.36498,0.97619,0.43540,0.36772,0.10713,0.20843,1.44395
Gabon,Sub-Saharan Africa,143,3.896,0.04547,1.06024,0.90528,0.43372,0.31914,0.11091,0.06822,0.99895
Niger,Sub-Saharan Africa,144,3.845,0.03602,0.06940,0.77265,0.29707,0.47692,0.15639,0.19387,1.87877
Cambodia,Southeastern Asia,145,3.819,0.05069,0.46038,0.62736,0.61114,0.66246,0.07247,0.40359,0.98195
Tanzania,Sub-Saharan Africa,146,3.781,0.05061,0.28520,1.00268,0.38215,0.32878,0.05747,0.34377,1.38079
Madagascar,Sub-Saharan Africa,147,3.681,0.03633,0.20824,0.66801,0.46721,0.19184,0.08124,0.21333,1.85100
Central African Republic,Sub-Saharan Africa,148,3.678,0.06112,0.07850,0.00000,0.06699,0.48879,0.08289,0.23835,2.72230
Chad,Sub-Saharan Africa,149,3.667,0.03830,0.34193,0.76062,0.15010,0.23501,0.05269,0.18386,1.94296
Guinea,Sub-Saharan Africa,150,3.656,0.03590,0.17417,0.46475,0.24009,0.37725,0.12139,0.28657,1.99172
Ivory Coast,Sub-Saharan Africa,151,3.655,0.05141,0.46534,0.77115,0.15185,0.46866,0.17922,0.20165,1.41723
Burkina Faso,Sub-Saharan Africa,152,3.587,0.04324,0.25812,0.85188,0.27125,0.39493,0.12832,0.21747,1.46494
Afghanistan,Southern Asia,153,3.575,0.03084,0.31982,0.30285,0.30335,0.23414,0.09719,0.36510,1.95210
Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [35]:
# 排序分层
report_2015_df2.sort_index(level=0)

                                                   Happiness Rank  \
Region                     Country
Australia and New Zealand  Australia                           10
                           New Zealand                          9
Central and Eastern Europe Albania                             95
                           Armenia                            127
                           Azerbaijan                          80
                           Belarus                             59
                           Bosnia and Herzegovina              96
                           Bulgaria                           134
                           Croatia                             62
                           Czech Republic                      31
                           Estonia                             73
                           Georgia                            130
                           Hungary                            104
                           Kazakhstan                          54
                           Kosovo                              69
                           Kyrgyzstan                          77
                           Latvia                              89
                           Lithuania                           56
                           Macedonia                           93
                           Moldova                             52
                           Montenegro                          82
                           Poland                              60
                           Romania                             86
                           Russia                              64
                           Serbia                              87
                           Slovakia                            45
                           Slovenia                            55
                           Tajikistan                         106
                           Turkmenistan                        70
                           Ukraine                            111
...                                                           ...
Sub-Saharan Africa         Somaliland region                   91
                           South Africa                       113
                           Sudan                              118
                           Swaziland                          101
                           Tanzania                           146
                           Togo                               158
                           Uganda                             141
                           Zambia                              85
                           Zimbabwe                           115
Western Europe             Austria                             13
                           Belgium                             19
                           Cyprus                              67
                           Denmark                              3
                           Finland                              6
                           France                              29
                           Germany                             26
                           Greece                             102
                           Iceland                              2
                           Ireland                             18
                           Italy                               50
                           Luxembourg                          17
                           Malta                               37
                           Netherlands                          7
                           North Cyprus                        66
                           Norway                               4
                           Portugal                            88
                           Spain                               36
                           Sweden                               8
                           Switzerland                          1
                           United Kingdom                      21

                                                   Happiness Score  \
Region                     Country
Australia and New Zealand  Australia                         7.284
                           New Zealand                       7.286
Central and Eastern Europe Albania                           4.959
                           Armenia                           4.350
                           Azerbaijan                        5.212
                           Belarus                           5.813
                           Bosnia and Herzegovina            4.949
                           Bulgaria                          4.218
                           Croatia                           5.759
                           Czech Republic                    6.505
                           Estonia                           5.429
                           Georgia                           4.297
                           Hungary                           4.800
                           Kazakhstan                        5.855
                           Kosovo                            5.589
                           Kyrgyzstan                        5.286
                           Latvia                            5.098
                           Lithuania                         5.833
                           Macedonia                         5.007
                           Moldova                           5.889
                           Montenegro                        5.192
                           Poland                            5.791
                           Romania                           5.124
                           Russia                            5.716
                           Serbia                            5.123
                           Slovakia                          5.995
                           Slovenia                          5.848
                           Tajikistan                        4.786
                           Turkmenistan                      5.548
                           Ukraine                           4.681
...                                                            ...
Sub-Saharan Africa         Somaliland region                 5.057
                           South Africa                      4.642
                           Sudan                             4.550
                           Swaziland                         4.867
                           Tanzania                          3.781
                           Togo                              2.839
                           Uganda                            3.931
                           Zambia                            5.129
                           Zimbabwe                          4.610
Western Europe             Austria                           7.200
                           Belgium                           6.937
                           Cyprus                            5.689
                           Denmark                           7.527
                           Finland                           7.406
                           France                            6.575
                           Germany                           6.750
                           Greece                            4.857
                           Iceland                           7.561
                           Ireland                           6.940
                           Italy                             5.948
                           Luxembourg                        6.946
                           Malta                             6.302
                           Netherlands                       7.378
                           North Cyprus                      5.695
                           Norway                            7.522
                           Portugal                          5.102
                           Spain                             6.329
                           Sweden                            7.364
                           Switzerland                       7.587
                           United Kingdom                    6.867

                                                   Standard Error  \
Region                     Country
Australia and New Zealand  Australia                      0.04083
                           New Zealand                    0.03371
Central and Eastern Europe Albania                        0.05013
                           Armenia                        0.04763
                           Azerbaijan                     0.03363
                           Belarus                        0.03938
                           Bosnia and Herzegovina         0.06913
                           Bulgaria                       0.04828
                           Croatia                        0.04394
                           Czech Republic                 0.04168
                           Estonia                        0.04013
                           Georgia                        0.04221
                           Hungary                        0.06107
                           Kazakhstan                     0.04114
                           Kosovo                         0.05018
                           Kyrgyzstan                     0.03823
                           Latvia                         0.04640
                           Lithuania                      0.03843
                           Macedonia                      0.05376
                           Moldova                        0.03799
                           Montenegro                     0.05235
                           Poland                         0.04263
                           Romania                        0.06607
                           Russia                         0.03135
                           Serbia                         0.04864
                           Slovakia                       0.04267
                           Slovenia                       0.04251
                           Tajikistan                     0.03198
                           Turkmenistan                   0.04175
                           Ukraine                        0.04412
...                                                           ...
Sub-Saharan Africa         Somaliland region              0.06161
                           South Africa                   0.04585
                           Sudan                          0.06740
                           Swaziland                      0.08742
                           Tanzania                       0.05061
                           Togo                           0.06727
                           Uganda                         0.04317
                           Zambia                         0.06988
                           Zimbabwe                       0.04290
Western Europe             Austria                        0.03751
                           Belgium                        0.03595
                           Cyprus                         0.05580
                           Denmark                        0.03328
                           Finland                        0.03140
                           France                         0.03512
                           Germany                        0.01848
                           Greece                         0.05062
                           Iceland                        0.04884
                           Ireland                        0.03676
                           Italy                          0.03914
                           Luxembourg                     0.03499
                           Malta                          0.04206
                           Netherlands                    0.02799
                           North Cyprus                   0.05635
                           Norway                         0.03880
                           Portugal                       0.04802
                           Spain                          0.03468
                           Sweden                         0.03157
                           Switzerland                    0.03411
                           United Kingdom                 0.01866

                                                   Economy (GDP per Capita)  \
Region                     Country
Australia and New Zealand  Australia                                1.33358
                           New Zealand                              1.25018
Central and Eastern Europe Albania                                  0.87867
                           Armenia                                  0.76821
                           Azerbaijan                               1.02389
                           Belarus                                  1.03192
                           Bosnia and Herzegovina                   0.83223
                           Bulgaria                                 1.01216
                           Croatia                                  1.08254
                           Czech Republic                           1.17898
                           Estonia                                  1.15174
                           Georgia                                  0.74190
                           Hungary                                  1.12094
                           Kazakhstan                               1.12254
                           Kosovo                                   0.80148
                           Kyrgyzstan                               0.47428
                           Latvia                                   1.11312
                           Lithuania                                1.14723
                           Macedonia                                0.91851
                           Moldova                                  0.59448
                           Montenegro                               0.97438
                           Poland                                   1.12555
                           Romania                                  1.04345
                           Russia                                   1.13764
                           Serbia                                   0.92053
                           Slovakia                                 1.16891
                           Slovenia                                 1.18498
                           Tajikistan                               0.39047
                           Turkmenistan                             0.95847
                           Ukraine                                  0.79907
...                                                                     ...
Sub-Saharan Africa         Somaliland region                        0.18847
                           South Africa                             0.92049
                           Sudan                                    0.52107
                           Swaziland                                0.71206
                           Tanzania                                 0.28520
                           Togo                                     0.20868
                           Uganda                                   0.21102
                           Zambia                                   0.47038
                           Zimbabwe                                 0.27100
Western Europe             Austria                                  1.33723
                           Belgium                                  1.30782
                           Cyprus                                   1.20813
                           Denmark                                  1.32548
                           Finland                                  1.29025
                           France                                   1.27778
                           Germany                                  1.32792
                           Greece                                   1.15406
                           Iceland                                  1.30232
                           Ireland                                  1.33596
                           Italy                                    1.25114
                           Luxembourg                               1.56391
                           Malta                                    1.20740
                           Netherlands                              1.32944
                           North Cyprus                             1.20806
                           Norway                                   1.45900
                           Portugal                                 1.15991
                           Spain                                    1.23011
                           Sweden                                   1.33171
                           Switzerland                              1.39651
                           United Kingdom                           1.26637

                                                    Family  \
Region                     Country
Australia and New Zealand  Australia               1.30923
                           New Zealand             1.31967
Central and Eastern Europe Albania                 0.80434
                           Armenia                 0.77711
                           Azerbaijan              0.93793
                           Belarus                 1.23289
                           Bosnia and Herzegovina  0.91916
                           Bulgaria                1.10614
                           Croatia                 0.79624
                           Czech Republic          1.20643
                           Estonia                 1.22791
                           Georgia                 0.38562
                           Hungary                 1.20215
                           Kazakhstan              1.12241
                           Kosovo                  0.81198
                           Kyrgyzstan              1.15115
                           Latvia                  1.09562
                           Lithuania               1.25745
                           Macedonia               1.00232
                           Moldova                 1.01528
                           Montenegro              0.90557
                           Poland                  1.27948
                           Romania                 0.88588
                           Russia                  1.23617
                           Serbia                  1.00964
                           Slovakia                1.26999
                           Slovenia                1.27385
                           Tajikistan              0.85563
                           Turkmenistan            1.22668
                           Ukraine                 1.20278
...                                                    ...
Sub-Saharan Africa         Somaliland region       0.95152
                           South Africa            1.18468
                           Sudan                   1.01404
                           Swaziland               1.07284
                           Tanzania                1.00268
                           Togo                    0.13995
                           Uganda                  1.13299
                           Zambia                  0.91612
                           Zimbabwe                1.03276
Western Europe             Austria                 1.29704
                           Belgium                 1.28566
                           Cyprus                  0.89318
                           Denmark                 1.36058
                           Finland                 1.31826